### ISSUE TITLE
build.sh does not work if you're not in its directory

### ISSUE THREAD

**Issue by gonX** [OpenTabletDriver/OpenTabletDriver#2942]
### Steps to Reproduce

```
cd <repo root>
mkdir test
cd test
../build.sh
```

### Expected Behavior

It builds

### Observed Behavior

It does not build, instead providing the error:

```
../build.sh: line 35: ./eng/linux/package.sh: No such file or directory
```

### Tablet Device

n/a

### Diagnostic Information

n/a

### Acknowledgements

- [X] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.
