### ISSUE TITLE
package.sh can result in possibly incorrect udev file

### ISSUE THREAD

**Issue by gonX** [OpenTabletDriver/OpenTabletDriver#2972]
### Steps to Reproduce

```
cd gitrepo
dotnet clean
eng/linux/package.sh --package Generic
```

### Expected Behavior

Should not contain garbage output:
```
$ head -n1 70-opentabletdriver.rules 
# Dynamically generated with the OpenTabletDriver.udev tool. https://github.com/OpenTabletDriver/OpenTabletDriver
```

### Observed Behavior

Contains garbage output:

```
$ head -n2 70-opentabletdriver.rules 
/home/gonx/git/opentabletdriver/OpenTabletDriver.Desktop/Interop/Input/MacOSVirtualMouse.cs(71,66): warning CS8629: Nullable value type may be null. [/home/gonx/git/opentabletdriver/OpenTabletDriver.Desktop/OpenTabletDriver.Desktop.csproj]
# Dynamically generated with the OpenTabletDriver.udev tool. https://github.com/OpenTabletDriver/OpenTabletDriver
```

### Tablet Device

n/a

### Diagnostic Information

n/a but 43c350ef57742

### Acknowledgements

- [ ] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

**Comment by gonX** [comment]
fixed by #2971

**Comment by gonX** [comment]
Worth noting this seems inconsistent, but `dotnet clean && dotnet run --project OpenTabletDriver.Tools.udev/ OpenTabletDriver.Configurations/Configurations/` seems to result in the same output - without the `clean` it doesn't always do it

**Comment by gonX** [comment]
Fixed with #2971
