### ISSUE TITLE
github-actions should not add `needs-triage` to issues if it already has nonstandard labels

### ISSUE THREAD

**Issue by gonX** [OpenTabletDriver/OpenTabletDriver#3250]
### Steps to Reproduce

1. Click "new issue" but do not submit the form yet
2. Set more labels than the currently offered default labels (e.g. `meta`)
3. Open issue

### Expected Behavior

The github-actions bot should not add the `needs-triage` label as the issue is likely already correctly triaged.

We only use the label for helping the Triage team make sure that the issue is labeled correctly.

Note that the check should be more specific than checking if the issue owner has permissions to set labels, as I've personally intentionally omitted additional labels for a later triage.

### Observed Behavior

The github-actions bot adds the `needs-triage` label.

### Tablet Device

n/a

### Diagnostic Information

n/a

### Acknowledgements

- [ ] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.
- [ ] I am on the latest version of OpenTabletDriver.

**Comment by jamesbt365** [comment]
Seems to be a limitation of the upstream labeler workflow, there is not currently a way to handle this.

**Comment by gonX** [comment]
As mentioned by James this seems not easily fixable. I think I will conclude it both not possible and not needed, as I sometimes find it useful to get a 2nd attempt at triage on some issues.
