### ISSUE TITLE
Automatic PR labeling

### ISSUE THREAD

**Issue by gonX** [OpenTabletDriver/OpenTabletDriver#3526]
### Description

GitHub's Issue labeler can be set to set labels based on file paths changed.

Here's my proposed list paths to match existing labels:
- `ci`: `.github/workflows/*`
- `configuration`: `OpenTabletDriver.Configuration/Configuration/*` or `OpenTabletDriver.Configuration/Parsers/*`
- `console`: `OpenTabletDriver.Console/*`
- `core`: `OpenTabletDriver/*`
- `daemon`: `OpenTabletDriver.Daemon/*` or `OpenTabletDriver.Daemon.*/*`
- `desktop`: `OpenTabletDriver.Desktop/*`
- `documentation`: `docs/*` or `README.md`
- `gui`: `OpenTabletDriver.UX/*` or `OpenTabletDriver.UX.*/*`
- `meta`: `.github/*`, `eng/*`, and anything in the root if possible
- `plugins`: `OpenTabletDriver.Plugin/*`(?)
- `tests`: `OpenTabletDriver.Tests/*`

OS specific labels are a bit more complex, as they can reference deep into the project, such as `OpenTabletDriver.Desktop/Interop/`. Therefore, any modified file containing the name of the OS in the path should probably be autolabeled as affecting that OS, e.g. `OpenTabletDriver.Desktop/Interop/Environment/LinuxEnvironmentHandler.cs` should detect as `linux/gtk`. 

However, these paths are generally useful to mark:
- `linux/gtk`:
  - `OpenTabletDriver.Native.Linux/*`
  - `OpenTabletDriver.UX.Gtk/*`
  - anything else containing `Linux` in the path
- `windows/wpf`:
  - `OpenTabletDriver/Devices/WinUSB/*`
  - `OpenTabletDriver.Native.Windows/*`
  - `OpenTabletDriver.UX.Wpf/*`
  - anything else containing `Windows` in the path
- `macos`:
  - `OpenTabletDriver.Native.MacOS/*`
  - `OpenTabletDriver.UX.MacOS/*`
  - anything else containing `MacOS` in the path

These paths will likely change as the project evolves. So a GitHub test should be made where the paths used in the issue labeler should still exist, so that e.g. merging #2772 which has breaking folder layout changes does at least knowingly break auto labeling.

The other `master` paths I am unable to determine a useful label for are:
- `OpenTabletDriver.Analyzers`
- `OpenTabletDriver.Analyzers.Tests`
- `OpenTabletDriver.Benchmarks`

Also worth noting that I looked at `master` for paths. These paths may be different on 0.6.x, but should still be included in the issue labeler.

Please let me know if you think I missed any important paths.

### Acknowledgements

- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.
- [ ] I am on the latest version of OpenTabletDriver.
